version: "3.9"

services:
  tests:
    image: api-tests
    container_name: api-tests
    restart: "no"
    command: ./run_tests.sh app/tests/
    env_file:
      - ../.env
    volumes:
      - report:/opt/api_tests/allure-result
    networks:
      - default

volumes:
  report:
    driver: local
